### ISSUE TITLE
Xamarin Studio Crash on StyleCop Settings

### ISSUE THREAD

**Issue by Verser** [DarkCloud14/MonoDevelop.StyleCop#19]
I am running into a problem where by clicking on StyleCop settings on a project, all of Xamarin Studio Mac 6.1.5. crashes.

No warning, hangs for about 5 seconds.

I've tried several different projects, including a new one.

Anyone else seen this issue before? Stylecop is the only non-default add-in installed. 

snippet of crash info below 
Process:               XamarinStudio [7046]
Path:                  /Applications/Xamarin Studio.app/Contents/MacOS/XamarinStudio
Identifier:            com.xamarin.xamarinstudio
Version:               6.1.5.0 (6.1.5.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           XamarinStudio [7046]
User ID:               2066577383

Date/Time:             2017-02-06 14:46:21.610 -0700
OS Version:            Mac OS X 10.11.6 (15G1212)
Report Version:        11
System Integrity Protection: enabled

Crashed Thread:        0  GUI Thread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000004280b80
Exception Note:        EXC_CORPSE_NOTIFY

External Modification Warnings:
Debugger attached to process.

VM Regions Near 0x4280b80:
--> 
    __TEXT                 0000000100194000-0000000100198000 [   16K] r-x/rwx SM=COW  /Applications/Xamarin Studio.app/Contents/MacOS/XamarinStudio

Application Specific Information:
abort() called

**Comment by DarkCloud14** [comment]
This is a duplicate, see issue #14 
I can't get this fixed as XamarinStudio since version 6 runs as 64bit and Mono doesn't have a XQuartz based System.Windows.Forms implementation for the 64bit runtime.

As soon as I get the time to get issue #4 done this shouldn't be a problem anymore, unfortunately I don't get the time right now to work on the project and don't know when I can work on it further..
